config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get '/user' => 'user#index'

  get '/sessions/create'

  get '/auth/:provider/callback' => 'sessions#create'

  get '/twitter' => 'sessions#new'

  get '/probs' => 'probs#index'

  get '/probs/new' => 'probs#new'

  post '/probs' => 'probs#create'

  get '/probs/:id' => 'probs#show', as: :prob

  delete '/probs/:id' => 'probs#destroy'

  get 'probs/:id/edit' => 'probs#edit', as: :edit_prob

  patch 'probs/:id' => 'probs#update'

  delete '/logout' => 'sessions#destroy'

end

app/models/prob.rb
class Prob < ActiveRecord::Base
  belongs_to :user
end

app/models/tweet.rb
require "httparty"
require "base64"


# {"token_type"=>"bearer", "access_token"=>"AAAAAAAAAAAAAAAAAAAAAApaugAAAAAA%2Bw7iy7XOsIoWUzn7yBpRwFgTAUo%3DSdBBY6luFSpFPSy8RuMg3jfm3JyTMBJGo0Kyc2zhhxKZgMxbAC"}


class Tweet
  def self.access_token
    url = "https://api.twitter.com/oauth2/token"
    enc = Base64.strict_encode64(ENV['twitter_key'] + ":" + ENV['twitter_secret'])
    # enc = Base64.strict_encode64("1532566392-yebjiVWs4s7bhIQETR4zFpqM1gkaeDiLb1gSVY0:88RXSqmv3nxMI4rNelAS0Vy4Fwfx4R6gW9vqtTcaJIbBZ")
    # body = "grant_type=client_credentials"
    response = HTTParty.post(url,
      :headers => {
        "Authorization" => "Basic #{enc}",
        "Content-Type"  => "application/x-www-form-urlencoded;charset=UTF-8",
        "User-Agent" => "My Twitter App"
      },
      :body => {
        "grant_type" => "client_credentials"
      },
      :debug_output => $stdout
    )
    access_token = response['access_token']
    url = "https://api.twitter.com/1.1/statuses/user_timeline.json?count=100&screen_name=twitterapi"
    response = HTTParty.get(url,
      :headers => {
        "Authorization" => "Bearer #{access_token}",
        "User-Agent" => "My Twitter App"
      },
      :debug_output => $stdout
    )
  end
end



# class User
#   url= "https://api.twitter.com/1.1/users/show.json"
#   enc= Base64.strict_encode64(ENV['twitter_key'] + ":" + ENV['twitter_secret'])
#   response = HTTParty.post(url,
#     :headers =>
#     "user_id" =>
#     "screen_name" =>
#     "include_entities" =>

request = Tweet.access_token
puts request

app/models/user.rb
class User < ActiveRecord::Base
  has_many :probs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
end

app/controllers/callbacks_controller.rb
class CallbacksController < ApplicationController




end

app/controllers/probs_controller.rb
class ProbsController < ApplicationController



  def index
    @user = User.find(session[:user_id])
    @probs = Prob.all
  end

  def new
    @user = User.find(session[:user_id])
    @prob = Prob.new
  end

  def edit
    @user = User.find(session[:user_id])
    @prob = Prob.find(params[:id])
  end

  def update
    @user = User.find(session[:user_id])
    @prob = Prob.find(params[:id])
    if @prob.update_attributes(prob_params)
      redirect_to prob_path(@prob)
    else
      render :edit
    end
  end

  def show
    @user = User.find(session[:user_id])
    @prob = Prob.find(params[:id])
  end

  def create
    @user = User.find(session[:user_id])
    @prob = @user.probs.new(prob_params)

    if @prob.save
      redirect_to prob_path(@prob.id)
    else
      render :new
    end
  end

  def destroy
    @user = User.find(session[:user_id])
    @prob = Prob.find(params[:id])
    @prob.destroy
    redirect_to probs_path
  end

private

  def prob_params
    params.require(:prob).permit(:word, :definition)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = from_omniauth(request.env['omniauth.auth'])
    session[:user_id] = @user.id
    flash[:success] = "Welcome, #{@user.name}!"
    redirect_to "/user"
  end

  def destroy
    session.delete(:user_id)
    @current_user = nil
    redirect_to '/'
  end

  private
  def from_omniauth(auth_hash)
    user = User.new(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.name = auth_hash['info']['name']
    user.location = auth_hash['info']['location']
    user.image_url = auth_hash['info']['image']
    user.url = auth_hash['info']['urls']['Twitter']
    user.save!
    user
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

before_action :create_client

#  def index
#     batch_size = 10
#     @twitter_handle = "dhh"
#     @tweets = @client.user_timeline(@twitter_handle).take(batch_size)
# end

def index
  @probs= Prob.all
end

def show
end

def new
  @Prob.new
end

def create
  @Prob.new(prob_params)

  if @prob.save
    redirect_to prob_path(@prob)
  else
    render :new
  end
end

def edit
end

def update
    if @prob.update_attributes(prob_params)
      redirect_to prob_path
    end
end

end

app/controllers/user_controller.rb
class UserController < ApplicationController

class << self
  def from_omniauth(auth_hash)
    user = find_or_create_by(uid: auth_hash['uid'], provider: auth_hash['provider'])
    user.name = auth_hash['info']['name']
    user.location = auth_hash['info']['location']
    user.image_url = auth_hash['info']['image']
    user.url = auth_hash['info']['urls']['Twitter']
    user.save!
    user
  end
end

def new
  @self= Self.new
end

def index
  @user = User.find(session[:user_id])
end

def show
  @user = User.find(session[:user_id])
  redirect_to('/') unless session[:uid]
end


  def update
    user = User.find_by(id: params[:id])
    user.update(user_params)
    redirect_to profile_path
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/callbacks_helper.rb
module CallbacksHelper
end

app/helpers/probs_helper.rb
module ProbsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AyprojectApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="nav navbar-nav">
  <%= link_to 'Sign into Twitter', '/auth/twitter?force_login=true' %>
  <%= link_to 'Log Out', logout_path, method: :delete %>
</div>



<%= yield %>



</body>
</html>

app/views/probs/_form.html.erb
<%= form_for(@prob) do |f| %>

  <div>
  <%= f.label(:word) %>
  <%= f.text_field(:word) %>
  </div>

  <div>
  <%= f.label(:definition) %>
  <%= f.text_area(:definition, size: "20x5") %>
  </div>

  <%= f.submit %>

<% end %>

app/views/probs/edit.html.erb
<h1>Edit your entry</h1>

<%= render 'form' %>

app/views/probs/index.html.erb
User: <%= @user.name %> <%= image_tag @user.image_url %>

<h1>Current Slang!</h1>

<%= link_to 'Add a word!', probs_new_path %>

<ul>
  <% @probs.each do |prob| %>
    <li>
      <%= link_to prob.word, prob_path(prob)%> by <%= prob.user.name %>
    </li>
  <% end %>
  </ul>

app/views/probs/new.html.erb
<h1>Add Your Word!</h1>

<%= render 'form' %>

app/views/probs/show.html.erb
<body>

<h3>Word: <%= @prob.word %></h3>
<p><%= @prob.definition %></p>

</body>

<%= link_to 'Edit your entry!', edit_prob_path(@prob.id) %>
<br>
<%= link_to 'Delete your word!', prob_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<br>
<%= link_to "View all words!", probs_path %>

app/views/user/index.html.erb
User: <%= @user.name %> <%= image_tag @user.image_url %>


<form method="get" action="/probs/new">
  <button type="submit">Add a word to the Twitionary!</button>
</form>

<form method="get" action="/probs">
  <button type="submit">View current entries</button>
</form>

app/views/user/new.html.erb
<h1>Login with Twitter</h1>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AYP</title>
</head>
<body>

<img src= "http://i.imgur.com/vdio0oH.png"></img>


<h1>About</h1>
<h3>Twitionary is an API intended for Twitter Users.

The evolution of slang is a quickly evolving beast. One day your mutuals could be saying 'dragged' or 'clocked', and the next day 'flop'. Don't even know what a mutual is? You're in the right place!

Any person with an active Twitter account can log in with their
account and can enter any slang with their definition. Users can also view what others have already submitted.

</h3>

</body>
</html>